name: Generate Directory Indexes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up previous index files
        run: |
          rm -f .github/index.html
          rm -f .github/workflows/index.html
          rm -f generate_index.sh

      - name: Create index generator script
        run: |
          echo '#!/bin/bash' > generate_index.sh
          echo 'generate_index() {' >> generate_index.sh
          echo '  dir="$1"' >> generate_index.sh
          echo '  if [ "$dir" = "." ]; then' >> generate_index.sh
          echo '    current_path="/"' >> generate_index.sh
          echo '  else' >> generate_index.sh
          echo '    current_path="/${dir#./}"' >> generate_index.sh
          echo '  fi' >> generate_index.sh
          echo '  echo "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Index of $current_path</title><style>body{font-family:Arial;margin:20px;}table{width:100%;border-collapse:collapse;}th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd;}th{background-color:#f2f2f2;}a{text-decoration:none;color:#0366d6;}a:hover{text-decoration:underline;}.dir{font-weight:bold;}</style></head><body><h1>Index of $current_path</h1><table><tr><th>Name</th><th>Size</th><th>Last Modified</th></tr>" > "$dir/index.html"' >> generate_index.sh
          echo '  if [ "$dir" != "." ]; then echo "<tr><td><a href=\"../\" class=\"dir\">../</a></td><td>-</td><td></td></tr>" >> "$dir/index.html"; fi' >> generate_index.sh
          echo '  # Get all items in directory except index.html, .git and .github' >> generate_index.sh
          echo '  items=$(find "$dir" -maxdepth 1 -mindepth 1 -not -name "index.html" -not -name ".git" -not -path "./.github/*")' >> generate_index.sh
          echo '  # Process each item and get Git timestamp for sorting' >> generate_index.sh
          echo '  echo "$items" | while read item; do' >> generate_index.sh
          echo '    if [ -e "$item" ]; then' >> generate_index.sh
          echo '      name=$(basename "$item")' >> generate_index.sh
          echo '      if [ -d "$item" ]; then' >> generate_index.sh
          echo '        # For directories, find all files in the directory except index.html and get the latest commit time' >> generate_index.sh
          echo '        timestamp=0' >> generate_index.sh
          echo '        for file in $(find "$item" -type f -not -name "index.html"); do' >> generate_index.sh
          echo '          file_timestamp=$(git log -1 --format="%ct" -- "$file" 2>/dev/null)' >> generate_index.sh
          echo '          if [ -n "$file_timestamp" ] && [ "$file_timestamp" -gt "$timestamp" ]; then' >> generate_index.sh
          echo '            timestamp=$file_timestamp' >> generate_index.sh
          echo '          fi' >> generate_index.sh
          echo '        done' >> generate_index.sh
          echo '        # If no files found (empty directory), use directory creation time' >> generate_index.sh
          echo '        if [ "$timestamp" -eq 0 ]; then' >> generate_index.sh
          echo '          timestamp=$(git log -1 --format="%ct" -- "$item" 2>/dev/null)' >> generate_index.sh
          echo '        fi' >> generate_index.sh
          echo '        class="dir"' >> generate_index.sh
          echo '        name="$name/"' >> generate_index.sh
          echo '        size="-"' >> generate_index.sh
          echo '      else' >> generate_index.sh
          echo '        # For files, get the latest commit time' >> generate_index.sh
          echo '        timestamp=$(git log -1 --format="%ct" -- "$item" 2>/dev/null)' >> generate_index.sh
          echo '        class=""' >> generate_index.sh
          echo '        # Get file size from Git' >> generate_index.sh
          echo '        size=$(git cat-file -s HEAD:"$item" 2>/dev/null)' >> generate_index.sh
          echo '        if [ -n "$size" ]; then' >> generate_index.sh
          echo '          if [ $size -ge 1048576 ]; then' >> generate_index.sh
          echo '            size=$(echo "scale=1; $size/1048576" | bc)MB' >> generate_index.sh
          echo '          elif [ $size -ge 1024 ]; then' >> generate_index.sh
          echo '            size=$(echo "scale=1; $size/1024" | bc)KB' >> generate_index.sh
          echo '          else' >> generate_index.sh
          echo '            size="${size}B"' >> generate_index.sh
          echo '          fi' >> generate_index.sh
          echo '        else' >> generate_index.sh
          echo '          size="-"' >> generate_index.sh
          echo '        fi' >> generate_index.sh
          echo '      fi' >> generate_index.sh
          echo '      # Convert timestamp to readable format' >> generate_index.sh
          echo '      if [ -n "$timestamp" ]; then' >> generate_index.sh
          echo '        mod_time=$(date -d "@$timestamp" "+%Y-%m-%d %H:%M" 2>/dev/null)' >> generate_index.sh
          echo '      else' >> generate_index.sh
          echo '        mod_time=""' >> generate_index.sh
          echo '      fi' >> generate_index.sh
          echo '      # Output for sorting' >> generate_index.sh
          echo '      echo "$timestamp|$class|$name|$size|$mod_time|$item"' >> generate_index.sh
          echo '    fi' >> generate_index.sh
          echo '  done | sort -t"|" -k2,2r -k1,1nr | while IFS="|" read -r timestamp class name size mod_time item; do' >> generate_index.sh          echo '    echo "<tr><td><a href=\"$name\" class=\"$class\">$name</a></td><td>$size</td><td>$mod_time</td></tr>" >> "$dir/index.html"' >> generate_index.sh
          echo '  done' >> generate_index.sh
          echo '  echo "</table></body></html>" >> "$dir/index.html"' >> generate_index.sh
          echo '}' >> generate_index.sh
          echo 'find . -type d -not -path "./.git/*" -not -path "./.github/*" | while read dir; do' >> generate_index.sh
          echo '  generate_index "$dir"' >> generate_index.sh
          echo 'done' >> generate_index.sh
    
          chmod +x generate_index.sh
          ./generate_index.sh

      - name: Commit and push index files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update directory indexes [skip ci]"
            git push
          fi
