name: Generate Directory Indexes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up previous index files
        run: |
          rm -f .github/index.html
          rm -f .github/workflows/index.html
          rm -f generate_index.sh

      - name: Create simple index generator script
        run: |
          echo '#!/bin/bash' > generate_index.sh
          echo 'find . -type d -not -path "./.git/*" -not -path "./.github/*" | while read dir; do' >> generate_index.sh
          echo '  echo "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>File List</title><style>body{font-family:Arial;margin:40px;}ul{list-style:none;padding:0;}li{margin:8px 0;}a{text-decoration:none;color:#0366d6;}a:hover{text-decoration:underline;}.dir{font-weight:bold;}</style></head><body><h1>File List</h1><ul>" > "$dir/index.html"' >> generate_index.sh
          echo '  if [ "$dir" != "." ]; then echo "<li><a href=\"../\" class=\"dir\">../</a></li>" >> "$dir/index.html"; fi' >> generate_index.sh
          echo '  for item in "$dir"/*; do' >> generate_index.sh
          echo '    if [ -e "$item" ]; then' >> generate_index.sh
          echo '      name=$(basename "$item")' >> generate_index.sh
          echo '      if [ "$name" != "index.html" ] && [ "$name" != ".git" ]; then' >> generate_index.sh
          echo '        if [ -d "$item" ]; then' >> generate_index.sh
          echo '          echo "<li><a href=\"$name/\" class=\"dir\">$name/</a></li>" >> "$dir/index.html"' >> generate_index.sh
          echo '        else' >> generate_index.sh
          echo '          echo "<li><a href=\"$name\">$name</a></li>" >> "$dir/index.html"' >> generate_index.sh
          echo '        fi' >> generate_index.sh
          echo '      fi' >> generate_index.sh
          echo '    fi' >> generate_index.sh
          echo '  done' >> generate_index.sh
          echo '  echo "</ul></body></html>" >> "$dir/index.html"' >> generate_index.sh
          echo 'done' >> generate_index.sh
          
          chmod +x generate_index.sh
          ./generate_index.sh

      - name: Clean up script file
        run: |
          rm -f generate_index.sh

      - name: Commit and push index files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update directory indexes [skip ci]"
            git push
          fi
