name: Generate Directory Indexes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate directory indexes
        run: |
          find . -type d -not -path "./.git/*" | while read dir; do
            cat > "$dir/index.html" << HTML_EOF
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>File List</title>
<style>
body { font-family: Arial, sans-serif; margin: 40px; }
ul { list-style: none; padding: 0; }
li { margin: 8px 0; }
a { text-decoration: none; color: #0366d6; }
a:hover { text-decoration: underline; }
.dir { font-weight: bold; }
</style>
</head>
<body>
<h1>File List</h1>
<ul>
HTML_EOF

            if [ "$dir" != "." ]; then
              echo '<li><a href="../" class="dir">../</a></li>' >> "$dir/index.html"
            fi

            for item in "$dir"/*; do
              if [ -e "$item" ]; then
                name=$(basename "$item")
                if [ "$name" != "index.html" ] && [ "$name" != ".git" ]; then
                  if [ -d "$item" ]; then
                    echo "<li><a href=\"$name/\" class=\"dir\">$name/</a></li>" >> "$dir/index.html"
                  else
                    echo "<li><a href=\"$name\">$name</a></li>" >> "$dir/index.html"
                  fi
                fi
              fi
            done

            cat >> "$dir/index.html" << HTML_EOF
</ul>
</body>
</html>
HTML_EOF
          done

      - name: Commit and push index files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update directory indexes [skip ci]"
            git push
          fi
