name: Generate Directory Indexes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up previous index files
        run: |
          rm -f .github/index.html
          rm -f .github/workflows/index.html
          rm -f generate_index.sh

      - name: Create index generator script
        run: |
          echo '#!/bin/bash' > generate_index.sh
          echo 'generate_index() {' >> generate_index.sh
          echo '  dir="$1"' >> generate_index.sh
          echo '  if [ "$dir" = "." ]; then' >> generate_index.sh
          echo '    current_path="/"' >> generate_index.sh
          echo '  else' >> generate_index.sh
          echo '    current_path="/${dir#./}"' >> generate_index.sh
          echo '  fi' >> generate_index.sh
          echo '  echo "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Index of $current_path</title><style>body{font-family:Arial;margin:20px;}table{width:100%;border-collapse:collapse;}th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd;}th{background-color:#f2f2f2;}a{text-decoration:none;color:#0366d6;}a:hover{text-decoration:underline;}.dir{font-weight:bold;}</style></head><body><h1>Index of $current_path</h1><table><tr><th>Name</th><th>Size</th><th>Last Modified</th></tr>" > "$dir/index.html"' >> generate_index.sh
          echo '  if [ "$dir" != "." ]; then echo "<tr><td><a href=\"../\" class=\"dir\">../</a></td><td>-</td><td></td></tr>" >> "$dir/index.html"; fi' >> generate_index.sh
          echo '  items=$(find "$dir" -maxdepth 1 -mindepth 1 -not -name "index.html" -not -name ".git" -not -path "./.github/*" -exec ls -td {} + | sort -f)' >> generate_index.sh
          echo '  echo "$items" | while read item; do' >> generate_index.sh
          echo '    if [ -e "$item" ]; then' >> generate_index.sh
          echo '      name=$(basename "$item")' >> generate_index.sh
          echo '      if [ -d "$item" ]; then' >> generate_index.sh
          echo '        class="dir"' >> generate_index.sh
          echo '        name="$name/"' >> generate_index.sh
          echo '        size="-"' >> generate_index.sh
          echo '      else' >> generate_index.sh
          echo '        class=""' >> generate_index.sh
          echo '        size=$(ls -lh "$item" | awk '\''{print $5}'\'')' >> generate_index.sh
          echo '      fi' >> generate_index.sh
          echo '      mod_time=$(ls -l --time-style="+%Y-%m-%d %H:%M" "$item" | awk '\''{print $6, $7}'\'')' >> generate_index.sh
          echo '      echo "<tr><td><a href=\"$name\" class=\"$class\">$name</a></td><td>$size</td><td>$mod_time</td></tr>" >> "$dir/index.html"' >> generate_index.sh
          echo '    fi' >> generate_index.sh
          echo '  done' >> generate_index.sh
          echo '  echo "</table></body></html>" >> "$dir/index.html"' >> generate_index.sh
          echo '}' >> generate_index.sh
          echo 'find . -type d -not -path "./.git/*" -not -path "./.github/*" | while read dir; do' >> generate_index.sh
          echo '  generate_index "$dir"' >> generate_index.sh
          echo 'done' >> generate_index.sh
    
          chmod +x generate_index.sh
          ./generate_index.sh

      - name: Commit and push index files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update directory indexes [skip ci]"
            git push
          fi
